# golangci-lint v2 configuration
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocyclo
    - gosec
    - misspell
    - unconvert
  disable:
    - lll
    - revive
    - unused
    - unparam
  exclusions:
    rules:
      # Exclude generated api.go file from all linters
      - path: "^api/api\\.go$"
        linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - gocyclo
          - gosec
          - misspell
          - unconvert
      # G117: Struct fields named Password/Secret/Token are intentional for OAuth, JWT, and DB config
      - linters:
          - gosec
        text: "G117:"
      # G101: False positives for secret key names, test credentials, and config structs
      - linters:
          - gosec
        text: "G101:"
      # G704: HTTP client calls are intentional (webhook delivery, OAuth token exchange)
      - linters:
          - gosec
        text: "G704:"
      # G115: Integer overflow conversions are safe in context (test helpers)
      - path: "_test\\.go$"
        linters:
          - gosec
        text: "G115:"

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0