package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/ericfitz/tmi/api/models"
	"github.com/ericfitz/tmi/internal/config"
	"github.com/ericfitz/tmi/internal/crypto"
	"github.com/ericfitz/tmi/internal/secrets"
	"github.com/ericfitz/tmi/internal/slogging"
	"github.com/ericfitz/tmi/test/testdb"
	"gopkg.in/yaml.v3"
)

// nonRoundTrippingKeys lists exported setting keys that export successfully
// from the database but do not correspond to a real config.Load path, so
// --import-config silently ignores them on the target database. Maintained
// by hand — detecting this generically would require walking the Config
// struct's yaml tags and diffing against the classification registry.
var nonRoundTrippingKeys = map[string]string{
	"session.timeout_minutes": "derived display value; the real source is auth.jwt.expiration_seconds",
	"features.saml_enabled":   "derived display path; the real source is auth.saml.providers.<id>.enabled",
	"auth.oauth_callback_url": "derived display value; real path is auth.oauth.callback_url",
}

// nonRoundTrippingKeysNote renders nonRoundTrippingKeys as a YAML comment
// block for the exported file header, documenting keys that will not
// survive a subsequent --import-config.
// SEM@b5c674dfdc4cb56dbaf09e2d041cd6a433f997f0: render known non-round-tripping export keys as a YAML comment block (pure)
func nonRoundTrippingKeysNote() string {
	if len(nonRoundTrippingKeys) == 0 {
		return ""
	}
	keys := make([]string, 0, len(nonRoundTrippingKeys))
	for k := range nonRoundTrippingKeys {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("#\n# NOTE: the following exported keys are derived/display-only values and do\n")
	b.WriteString("# NOT round-trip via --import-config (no corresponding config.Load path):\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "#   - %s (%s)\n", k, nonRoundTrippingKeys[k])
	}
	return b.String()
}

// exportRow is one system_settings row prepared for YAML export.
// SEM@7e3bc19f8950c8b27a14cef539ae7dff89e30a7a: DTO holding a decrypted system_settings row for YAML export (pure)
type exportRow struct {
	Key   string
	Value string
	Type  string
}

// buildNestedConfig converts dotted setting keys into a nested map, coercing
// values per setting_type so the YAML round-trips through config.Load.
// SEM@7e3bc19f8950c8b27a14cef539ae7dff89e30a7a: convert dotted export rows into a nested map with type-coerced values (pure)
func buildNestedConfig(rows []exportRow) map[string]any {
	root := make(map[string]any)
	for _, r := range rows {
		var val any = r.Value
		switch r.Type {
		case "bool":
			if b, err := strconv.ParseBool(r.Value); err == nil {
				val = b
			}
		case "int":
			if n, err := strconv.Atoi(r.Value); err == nil {
				val = n
			}
		case "float":
			if f, err := strconv.ParseFloat(r.Value, 64); err == nil {
				val = f
			}
		case "json":
			// json-typed settings (e.g. administrators, CORS allowed_origins,
			// OAuth client_callback_allowlist) must decode to a real
			// structure, not a YAML string scalar — otherwise config.Load's
			// yaml.Unmarshal into the typed field fails and --import-config
			// aborts the whole import. Fall back to the raw string (prior
			// behavior) if the stored value isn't valid JSON.
			var decoded any
			if err := json.Unmarshal([]byte(r.Value), &decoded); err == nil {
				val = decoded
			} else {
				slogging.Get().Warn("Failed to decode json-typed setting %s for export, keeping raw string: %v", r.Key, err)
			}
		}
		parts := strings.Split(r.Key, ".")
		current := root
		for i, part := range parts {
			if i == len(parts)-1 {
				current[part] = val
				continue
			}
			if _, ok := current[part]; !ok {
				current[part] = make(map[string]any)
			}
			if next, ok := current[part].(map[string]any); ok {
				current = next
			}
		}
	}
	return root
}

// writeExportedConfig serializes rows as nested YAML with a provenance header.
// SEM@7e3bc19f8950c8b27a14cef539ae7dff89e30a7a: serialize export rows as nested YAML with a provenance header (writes file)
func writeExportedConfig(rows []exportRow, outputPath string) error {
	header := fmt.Sprintf("# TMI operational settings exported from database\n"+
		"# Generated by tmi-dbtool --export-config on %s\n"+
		"# Import into a target database with: tmi-dbtool --import-config -f <this file>\n"+
		"%s\n",
		time.Now().UTC().Format(time.RFC3339), nonRoundTrippingKeysNote())
	yamlData, err := yaml.Marshal(buildNestedConfig(rows))
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}
	return os.WriteFile(outputPath, append([]byte(header), yamlData...), 0o600)
}

// runConfigExport reads all system_settings rows and writes them as a nested
// YAML config file suitable for --import-config into another database.
// Secret settings are decrypted when an encryptor is available and
// decryptSecrets is true; otherwise they are skipped with a warning (an
// encrypted blob is useless across databases with different keys).
// SEM@0000000000000000000000000000000000000000: export system_settings rows to YAML, skipping secret/empty values (reads DB, writes file)
func runConfigExport(db *testdb.TestDB, cfgPath, outputFile string, decryptSecrets bool) error {
	log := slogging.Get()

	cfg, err := config.Load(cfgPath)
	if err != nil {
		return fmt.Errorf("failed to load config %s: %w", cfgPath, err)
	}

	// Identify which keys are secret, and what type each key is declared as
	// (same source of truth the import uses).
	secretKeys := make(map[string]bool)
	declaredTypes := make(map[string]string)
	for _, s := range cfg.GetMigratableSettings() {
		if s.Secret {
			secretKeys[s.Key] = true
		}
		declaredTypes[s.Key] = s.Type
	}

	var encryptor *crypto.SettingsEncryptor
	if decryptSecrets {
		if provider, perr := secrets.NewProvider(context.Background(), &cfg.Secrets); perr == nil {
			if enc, eerr := crypto.NewSettingsEncryptor(context.Background(), provider); eerr == nil {
				encryptor = enc
			}
			if closeErr := provider.Close(); closeErr != nil {
				log.Debug("Failed to close secrets provider: %v", closeErr)
			}
		}
	}

	var settings []models.SystemSetting
	if err := db.DB().Order("setting_key").Find(&settings).Error; err != nil {
		return fmt.Errorf("failed to read system_settings: %w", err)
	}

	var rows []exportRow
	var skippedSecrets int
	var skippedEmpty int
	for _, s := range settings {
		key := string(s.SettingKey)
		value := string(s.Value)
		if reason, ok := nonRoundTrippingKeys[key]; ok {
			log.Warn("Setting %s exports but will not round-trip via --import-config: %s", key, reason)
		}
		if secretKeys[key] {
			// NewSettingsEncryptor returns a non-nil but disabled encryptor
			// (not an error) when no key is configured, so encryptor == nil
			// alone does not catch "no key available" — it only catches
			// decryptSecrets == false or secrets-provider construction
			// failure. Check IsEnabled() too, otherwise Decrypt would hard
			// error on an ENC:-prefixed value instead of skipping it.
			if encryptor == nil || !encryptor.IsEnabled() {
				skippedSecrets++
				log.Warn("Skipping secret setting %s (no decryptor available)", key)
				continue
			}
			plain, derr := encryptor.Decrypt(value)
			if derr != nil {
				return fmt.Errorf("failed to decrypt setting %s: %w", key, derr)
			}
			value = plain
		}
		// Skip empty values, mirroring the import-side skip in runConfigSeed
		// (cmd/dbtool/config.go): on Oracle ADB an empty string bound to a
		// CLOB column is NULL, which violates the NOT NULL constraint on
		// system_settings.value (ORA-01400). Exporting an empty value would
		// just produce a file --import-config silently discards on Postgres
		// and hard-fails on Oracle, so skip it here too and keep both seed
		// paths in lockstep (#549).
		if value == "" {
			skippedEmpty++
			log.Warn("Skipping empty setting %s (not portable; import skips empty values — Oracle stores '' as NULL, ORA-01400)", key)
			continue
		}
		// Prefer the type the config registry declares for this key over the
		// one stored on the row. The stored setting_type is only as good as
		// whatever wrote it, and it has drifted: observability.sampling_rate
		// was seeded as "string" while the struct field is a float64, so the
		// export emitted `sampling_rate: "1"` and --import-config then died on
		// `cannot unmarshal !!str into float64` — the round-trip this file's
		// own header advertises. Trusting the registry fixes already-seeded
		// databases without needing a data migration to correct their rows.
		typ := string(s.SettingType)
		if declared, ok := declaredTypes[key]; ok && declared != "" {
			typ = declared
		}
		rows = append(rows, exportRow{Key: key, Value: value, Type: typ})
	}

	if err := writeExportedConfig(rows, outputFile); err != nil {
		return fmt.Errorf("failed to write export: %w", err)
	}
	log.Info("Exported %d settings to %s (%d secrets skipped, %d empty skipped)", len(rows), outputFile, skippedSecrets, skippedEmpty)
	return nil
}
