package main

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/ericfitz/tmi/api/models"
	"github.com/ericfitz/tmi/internal/config"
	"github.com/ericfitz/tmi/internal/crypto"
	"github.com/ericfitz/tmi/internal/secrets"
	"github.com/ericfitz/tmi/internal/slogging"
	"github.com/ericfitz/tmi/test/testdb"
	"gopkg.in/yaml.v3"
)

// exportRow is one system_settings row prepared for YAML export.
// SEM@7e3bc19f8950c8b27a14cef539ae7dff89e30a7a: DTO holding a decrypted system_settings row for YAML export (pure)
type exportRow struct {
	Key   string
	Value string
	Type  string
}

// buildNestedConfig converts dotted setting keys into a nested map, coercing
// values per setting_type so the YAML round-trips through config.Load.
// SEM@7e3bc19f8950c8b27a14cef539ae7dff89e30a7a: convert dotted export rows into a nested map with type-coerced values (pure)
func buildNestedConfig(rows []exportRow) map[string]any {
	root := make(map[string]any)
	for _, r := range rows {
		var val any = r.Value
		switch r.Type {
		case "bool":
			if b, err := strconv.ParseBool(r.Value); err == nil {
				val = b
			}
		case "int":
			if n, err := strconv.Atoi(r.Value); err == nil {
				val = n
			}
		}
		parts := strings.Split(r.Key, ".")
		current := root
		for i, part := range parts {
			if i == len(parts)-1 {
				current[part] = val
				continue
			}
			if _, ok := current[part]; !ok {
				current[part] = make(map[string]any)
			}
			if next, ok := current[part].(map[string]any); ok {
				current = next
			}
		}
	}
	return root
}

// writeExportedConfig serializes rows as nested YAML with a provenance header.
// SEM@7e3bc19f8950c8b27a14cef539ae7dff89e30a7a: serialize export rows as nested YAML with a provenance header (writes file)
func writeExportedConfig(rows []exportRow, outputPath string) error {
	header := fmt.Sprintf("# TMI operational settings exported from database\n"+
		"# Generated by tmi-dbtool --export-config on %s\n"+
		"# Import into a target database with: tmi-dbtool --import-config -f <this file>\n\n",
		time.Now().UTC().Format(time.RFC3339))
	yamlData, err := yaml.Marshal(buildNestedConfig(rows))
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}
	return os.WriteFile(outputPath, append([]byte(header), yamlData...), 0o600)
}

// runConfigExport reads all system_settings rows and writes them as a nested
// YAML config file suitable for --import-config into another database.
// Secret settings are decrypted when an encryptor is available and
// decryptSecrets is true; otherwise they are skipped with a warning (an
// encrypted blob is useless across databases with different keys).
// SEM@7e3bc19f8950c8b27a14cef539ae7dff89e30a7a: export system_settings rows to a nested YAML config file, optionally decrypting secrets (reads DB, writes file)
func runConfigExport(db *testdb.TestDB, cfgPath, outputFile string, decryptSecrets bool) error {
	log := slogging.Get()

	cfg, err := config.Load(cfgPath)
	if err != nil {
		return fmt.Errorf("failed to load config %s: %w", cfgPath, err)
	}

	// Identify which keys are secret (same source of truth the import uses).
	secretKeys := make(map[string]bool)
	for _, s := range cfg.GetMigratableSettings() {
		if s.Secret {
			secretKeys[s.Key] = true
		}
	}

	var encryptor *crypto.SettingsEncryptor
	if decryptSecrets {
		if provider, perr := secrets.NewProvider(context.Background(), &cfg.Secrets); perr == nil {
			if enc, eerr := crypto.NewSettingsEncryptor(context.Background(), provider); eerr == nil {
				encryptor = enc
			}
			if closeErr := provider.Close(); closeErr != nil {
				log.Debug("Failed to close secrets provider: %v", closeErr)
			}
		}
	}

	var settings []models.SystemSetting
	if err := db.DB().Order("setting_key").Find(&settings).Error; err != nil {
		return fmt.Errorf("failed to read system_settings: %w", err)
	}

	var rows []exportRow
	var skippedSecrets int
	for _, s := range settings {
		key := string(s.SettingKey)
		value := string(s.Value)
		if secretKeys[key] {
			if encryptor == nil {
				skippedSecrets++
				log.Warn("Skipping secret setting %s (no decryptor available)", key)
				continue
			}
			plain, derr := encryptor.Decrypt(value)
			if derr != nil {
				return fmt.Errorf("failed to decrypt setting %s: %w", key, derr)
			}
			value = plain
		}
		rows = append(rows, exportRow{Key: key, Value: value, Type: string(s.SettingType)})
	}

	if err := writeExportedConfig(rows, outputFile); err != nil {
		return fmt.Errorf("failed to write export: %w", err)
	}
	log.Info("Exported %d settings to %s (%d secrets skipped)", len(rows), outputFile, skippedSecrets)
	return nil
}
