-- ============================================================================
-- CONSOLIDATED BUSINESS DOMAIN MIGRATION
-- This migration creates all business domain tables with proper user foreign
-- keys using internal_uuid and descriptive naming conventions.
-- ============================================================================

-- Create threat_models table with UUID-based ownership
CREATE TABLE IF NOT EXISTS threat_models (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    owner_internal_uuid UUID NOT NULL REFERENCES users(internal_uuid) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    description TEXT,
    created_by TEXT NOT NULL,  -- Email for audit trail (denormalized)
    threat_model_framework TEXT NOT NULL DEFAULT 'STRIDE'
        CHECK (threat_model_framework IN ('CIA', 'STRIDE', 'LINDDUN', 'DIE', 'PLOT4ai')),
    issue_uri TEXT,
    status TEXT CHECK (status IS NULL OR length(status) <= 128),
    status_updated TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create diagrams table
CREATE TABLE IF NOT EXISTS diagrams (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    threat_model_id UUID NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('DFD-1.0.0')),
    content TEXT,
    cells JSONB,
    svg_image TEXT,
    image_update_vector BIGINT,
    update_vector BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create assets table (must be created before threats table due to FK dependency)
CREATE TABLE IF NOT EXISTS assets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    threat_model_id UUID NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL CHECK (type IN ('data', 'hardware', 'software', 'infrastructure', 'service', 'personnel')),
    criticality TEXT,
    classification TEXT[],
    sensitivity TEXT[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create threats table (UUID generated by application using UUIDv7)
CREATE TABLE IF NOT EXISTS threats (
    id UUID PRIMARY KEY,
    threat_model_id UUID NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    diagram_id UUID REFERENCES diagrams(id) ON DELETE SET NULL,
    cell_id UUID,
    asset_id UUID REFERENCES assets(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    severity TEXT,  -- No constraint - allows numeric, English, localized, or custom values
    likelihood TEXT,
    risk_level TEXT,
    score DECIMAL(3,1) CHECK (score >= 0.0 AND score <= 10.0),
    priority TEXT DEFAULT 'Medium',
    mitigated BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'Active',
    threat_type TEXT DEFAULT 'Unspecified',
    mitigation TEXT,
    issue_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create threat_model_access table for authorization (UUID-based subjects)
CREATE TABLE IF NOT EXISTS threat_model_access (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    threat_model_id UUID NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    subject_internal_uuid UUID NOT NULL REFERENCES users(internal_uuid) ON DELETE CASCADE,
    subject_type TEXT NOT NULL DEFAULT 'user' CHECK (subject_type IN ('user', 'group')),
    idp TEXT,  -- Identity provider (for groups, optional for users)
    role TEXT NOT NULL CHECK (role IN ('owner', 'writer', 'reader')),
    granted_by_internal_uuid UUID REFERENCES users(internal_uuid) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(threat_model_id, subject_internal_uuid, subject_type)
);

-- Create documents table
CREATE TABLE documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    threat_model_id UUID NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    uri TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create notes table
CREATE TABLE notes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    threat_model_id UUID NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create repositories table
CREATE TABLE repositories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    threat_model_id UUID NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    name TEXT,
    uri TEXT NOT NULL,
    description TEXT,
    type TEXT CHECK (type IN ('git', 'svn', 'mercurial', 'other')),
    parameters JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create metadata table (UUID generated by application using UUIDv7)
CREATE TABLE metadata (
    id UUID PRIMARY KEY,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('threat_model', 'threat', 'diagram', 'document', 'repository', 'cell', 'note', 'asset')),
    entity_id UUID NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key constraints for collaboration_sessions (deferred from file 1)
ALTER TABLE collaboration_sessions ADD FOREIGN KEY (threat_model_id) REFERENCES threat_models(id) ON DELETE CASCADE;
ALTER TABLE collaboration_sessions ADD FOREIGN KEY (diagram_id) REFERENCES diagrams(id) ON DELETE CASCADE;

-- Create webhook_subscriptions table
CREATE TABLE IF NOT EXISTS webhook_subscriptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    owner_internal_uuid UUID NOT NULL REFERENCES users(internal_uuid) ON DELETE CASCADE,
    threat_model_id UUID REFERENCES threat_models(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    events TEXT[] NOT NULL,
    secret TEXT,
    status TEXT NOT NULL DEFAULT 'pending_verification'
        CHECK (status IN ('pending_verification', 'active', 'pending_delete')),
    challenge TEXT,
    challenges_sent INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_successful_use TIMESTAMPTZ,
    publication_failures INT NOT NULL DEFAULT 0
);

-- Create webhook_deliveries table (using UUIDv7 for time-ordered IDs)
CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id UUID PRIMARY KEY,
    subscription_id UUID NOT NULL REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'delivered', 'failed')),
    attempts INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ
);

-- Create webhook_quotas table for per-owner rate limits
CREATE TABLE IF NOT EXISTS webhook_quotas (
    owner_internal_uuid UUID PRIMARY KEY REFERENCES users(internal_uuid) ON DELETE CASCADE,
    max_subscriptions INT NOT NULL DEFAULT 10,
    max_events_per_minute INT NOT NULL DEFAULT 12,
    max_subscription_requests_per_minute INT NOT NULL DEFAULT 10,
    max_subscription_requests_per_day INT NOT NULL DEFAULT 20,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create webhook_url_deny_list table for SSRF prevention
CREATE TABLE IF NOT EXISTS webhook_url_deny_list (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    pattern TEXT NOT NULL,
    pattern_type TEXT NOT NULL CHECK (pattern_type IN ('glob', 'regex')),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create administrators table
CREATE TABLE IF NOT EXISTS administrators (
    user_internal_uuid UUID NOT NULL REFERENCES users(internal_uuid) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    subject_type TEXT NOT NULL CHECK (subject_type IN ('user', 'group')),
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by_internal_uuid UUID REFERENCES users(internal_uuid) ON DELETE SET NULL,
    notes TEXT,
    PRIMARY KEY (user_internal_uuid, subject, subject_type)
);

-- Create addons table
CREATE TABLE IF NOT EXISTS addons (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    webhook_id UUID NOT NULL REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
    description TEXT,
    icon TEXT,
    objects TEXT[],
    threat_model_id UUID REFERENCES threat_models(id) ON DELETE CASCADE
);

-- Create addon_invocation_quotas table
CREATE TABLE IF NOT EXISTS addon_invocation_quotas (
    owner_internal_uuid UUID PRIMARY KEY REFERENCES users(internal_uuid) ON DELETE CASCADE,
    max_active_invocations INT NOT NULL DEFAULT 1,
    max_invocations_per_hour INT NOT NULL DEFAULT 10,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create user_api_quotas table for per-user API rate limits
CREATE TABLE IF NOT EXISTS user_api_quotas (
    user_internal_uuid UUID PRIMARY KEY REFERENCES users(internal_uuid) ON DELETE CASCADE,
    max_requests_per_minute INT NOT NULL DEFAULT 100,
    max_requests_per_hour INT DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create authorization_groups table to track groups used in authorizations
CREATE TABLE IF NOT EXISTS authorization_groups (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    idp TEXT NOT NULL,
    group_name TEXT NOT NULL,
    display_name TEXT,
    first_used TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usage_count INTEGER DEFAULT 1,
    UNIQUE(idp, group_name)
);

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- Pre-create the "everyone" pseudo-group with the flag UUID
-- This special group grants access to all authenticated users
INSERT INTO authorization_groups (id, idp, group_name, display_name, usage_count)
VALUES (
    '00000000-0000-0000-0000-000000000000'::uuid,
    '*',
    'everyone',
    'Everyone (Pseudo-group)',
    0
)
ON CONFLICT (idp, group_name) DO NOTHING;

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Indexes for threat_models
CREATE INDEX idx_threat_models_owner_internal_uuid ON threat_models(owner_internal_uuid);
CREATE INDEX idx_threat_models_framework ON threat_models(threat_model_framework);
CREATE INDEX idx_threat_models_created_by ON threat_models(created_by);
CREATE INDEX idx_threat_models_owner_created_at ON threat_models(owner_internal_uuid, created_at DESC);
CREATE INDEX idx_threat_models_status ON threat_models(status) WHERE status IS NOT NULL;
CREATE INDEX idx_threat_models_status_updated ON threat_models(status_updated);

-- Indexes for diagrams
CREATE INDEX idx_diagrams_threat_model_id ON diagrams(threat_model_id);
CREATE INDEX idx_diagrams_type ON diagrams(type);
CREATE INDEX idx_diagrams_cells ON diagrams USING GIN (cells);
CREATE INDEX idx_diagrams_threat_model_id_type ON diagrams(threat_model_id, type);

-- Indexes for threats
CREATE INDEX idx_threats_threat_model_id ON threats(threat_model_id);
CREATE INDEX idx_threats_severity ON threats(severity) WHERE severity IS NOT NULL;
CREATE INDEX idx_threats_risk_level ON threats(risk_level) WHERE risk_level IS NOT NULL;
CREATE INDEX idx_threats_diagram_id ON threats(diagram_id);
CREATE INDEX idx_threats_cell_id ON threats(cell_id);
CREATE INDEX idx_threats_asset_id ON threats(asset_id);
CREATE INDEX idx_threats_priority ON threats(priority);
CREATE INDEX idx_threats_mitigated ON threats(mitigated);
CREATE INDEX idx_threats_status ON threats(status);
CREATE INDEX idx_threats_threat_type ON threats(threat_type);
CREATE INDEX idx_threats_score ON threats(score);
CREATE INDEX idx_threats_name ON threats(name);
CREATE INDEX idx_threats_modified_at ON threats(modified_at);
CREATE INDEX idx_threats_threat_model_created_at ON threats(threat_model_id, created_at DESC);
CREATE INDEX idx_threats_threat_model_modified_at ON threats(threat_model_id, modified_at DESC);

-- Indexes for threat_model_access
CREATE INDEX idx_threat_model_access_threat_model_id ON threat_model_access(threat_model_id);
CREATE INDEX idx_threat_model_access_subject_internal_uuid ON threat_model_access(subject_internal_uuid);
CREATE INDEX idx_threat_model_access_subject_type ON threat_model_access(subject_type);
CREATE INDEX idx_threat_model_access_idp ON threat_model_access(idp) WHERE idp IS NOT NULL;
CREATE INDEX idx_threat_model_access_role ON threat_model_access(role);
CREATE INDEX idx_threat_model_access_performance ON threat_model_access(threat_model_id, subject_type, subject_internal_uuid);

-- Indexes for documents
CREATE INDEX idx_documents_threat_model_id ON documents(threat_model_id);
CREATE INDEX idx_documents_name ON documents(name);
CREATE INDEX idx_documents_created_at ON documents(created_at);
CREATE INDEX idx_documents_modified_at ON documents(modified_at);
CREATE INDEX idx_documents_threat_model_created_at ON documents(threat_model_id, created_at DESC);
CREATE INDEX idx_documents_threat_model_modified_at ON documents(threat_model_id, modified_at DESC);

-- Indexes for notes
CREATE INDEX idx_notes_threat_model_id ON notes(threat_model_id);
CREATE INDEX idx_notes_name ON notes(name);
CREATE INDEX idx_notes_created_at ON notes(created_at);
CREATE INDEX idx_notes_modified_at ON notes(modified_at);
CREATE INDEX idx_notes_threat_model_created_at ON notes(threat_model_id, created_at DESC);
CREATE INDEX idx_notes_threat_model_modified_at ON notes(threat_model_id, modified_at DESC);

-- Indexes for repositories
CREATE INDEX idx_repositories_threat_model_id ON repositories(threat_model_id);
CREATE INDEX idx_repositories_name ON repositories(name);
CREATE INDEX idx_repositories_type ON repositories(type);
CREATE INDEX idx_repositories_created_at ON repositories(created_at);
CREATE INDEX idx_repositories_modified_at ON repositories(modified_at);
CREATE INDEX idx_repositories_threat_model_created_at ON repositories(threat_model_id, created_at DESC);
CREATE INDEX idx_repositories_threat_model_modified_at ON repositories(threat_model_id, modified_at DESC);

-- Indexes for assets
CREATE INDEX idx_assets_threat_model_id ON assets(threat_model_id);
CREATE INDEX idx_assets_name ON assets(name);
CREATE INDEX idx_assets_type ON assets(type);
CREATE INDEX idx_assets_created_at ON assets(created_at);
CREATE INDEX idx_assets_modified_at ON assets(modified_at);
CREATE INDEX idx_assets_threat_model_created_at ON assets(threat_model_id, created_at DESC);
CREATE INDEX idx_assets_threat_model_modified_at ON assets(threat_model_id, modified_at DESC);

-- Indexes for metadata
CREATE INDEX idx_metadata_entity_type_id ON metadata(entity_type, entity_id);
CREATE INDEX idx_metadata_key ON metadata(key);
CREATE INDEX idx_metadata_entity_id ON metadata(entity_id);
CREATE UNIQUE INDEX idx_metadata_unique_key_per_entity ON metadata(entity_type, entity_id, key);
CREATE INDEX idx_metadata_key_value ON metadata(key, value);
CREATE INDEX idx_metadata_entity_key_exists ON metadata(entity_type, entity_id, key) WHERE value IS NOT NULL;
CREATE INDEX idx_metadata_created_at ON metadata(created_at);
CREATE INDEX idx_metadata_modified_at ON metadata(modified_at);
CREATE INDEX idx_metadata_entity_type_created_at ON metadata(entity_type, created_at DESC);
CREATE INDEX idx_metadata_entity_type_modified_at ON metadata(entity_type, modified_at DESC);

-- Partial indexes for specific entity types in metadata
CREATE INDEX idx_metadata_threats ON metadata(entity_id, key, value) WHERE entity_type = 'threat';
CREATE INDEX idx_metadata_documents ON metadata(entity_id, key, value) WHERE entity_type = 'document';
CREATE INDEX idx_metadata_notes ON metadata(entity_id, key, value) WHERE entity_type = 'note';
CREATE INDEX idx_metadata_repositories ON metadata(entity_id, key, value) WHERE entity_type = 'repository';
CREATE INDEX idx_metadata_diagrams ON metadata(entity_id, key, value) WHERE entity_type = 'diagram';
CREATE INDEX idx_metadata_threat_models ON metadata(entity_id, key, value) WHERE entity_type = 'threat_model';
CREATE INDEX idx_metadata_assets ON metadata(entity_id, key, value) WHERE entity_type = 'asset';

-- Performance indexes for authorization inheritance
CREATE INDEX idx_threats_owner_via_threat_model ON threats(threat_model_id)
    INCLUDE (id, name, created_at, modified_at);
CREATE INDEX idx_documents_owner_via_threat_model ON documents(threat_model_id)
    INCLUDE (id, name, uri, created_at, modified_at);
CREATE INDEX idx_notes_owner_via_threat_model ON notes(threat_model_id)
    INCLUDE (id, name, created_at, modified_at);
CREATE INDEX idx_repositories_owner_via_threat_model ON repositories(threat_model_id)
    INCLUDE (id, name, uri, type, created_at, modified_at);
CREATE INDEX idx_assets_owner_via_threat_model ON assets(threat_model_id)
    INCLUDE (id, name, type, created_at, modified_at);

-- Indexes for webhook_subscriptions
CREATE INDEX idx_webhook_subscriptions_owner ON webhook_subscriptions(owner_internal_uuid);
CREATE INDEX idx_webhook_subscriptions_threat_model ON webhook_subscriptions(threat_model_id) WHERE threat_model_id IS NOT NULL;
CREATE INDEX idx_webhook_subscriptions_status ON webhook_subscriptions(status);
CREATE INDEX idx_webhook_subscriptions_pending_verification ON webhook_subscriptions(status, challenges_sent, created_at) WHERE status = 'pending_verification';
CREATE INDEX idx_webhook_subscriptions_active ON webhook_subscriptions(status) WHERE status = 'active';

-- Indexes for webhook_deliveries
CREATE INDEX idx_webhook_deliveries_subscription ON webhook_deliveries(subscription_id);
CREATE INDEX idx_webhook_deliveries_status_retry ON webhook_deliveries(status, next_retry_at) WHERE status = 'pending';
CREATE INDEX idx_webhook_deliveries_created ON webhook_deliveries(created_at);

-- Index for webhook_url_deny_list
CREATE INDEX idx_webhook_url_deny_list_pattern_type ON webhook_url_deny_list(pattern_type);

-- Indexes for administrators
CREATE INDEX idx_administrators_subject ON administrators(subject);
CREATE INDEX idx_administrators_subject_type ON administrators(subject_type);
CREATE INDEX idx_administrators_granted_at ON administrators(granted_at DESC);

-- Indexes for addons
CREATE INDEX idx_addons_webhook ON addons(webhook_id);
CREATE INDEX idx_addons_threat_model ON addons(threat_model_id) WHERE threat_model_id IS NOT NULL;
CREATE INDEX idx_addons_created_at ON addons(created_at DESC);

-- Index for addon_invocation_quotas
CREATE INDEX idx_addon_invocation_quotas_owner ON addon_invocation_quotas(owner_internal_uuid);

-- Index for user_api_quotas
CREATE INDEX idx_user_api_quotas_user ON user_api_quotas(user_internal_uuid);

-- Indexes for authorization_groups
CREATE INDEX idx_authorization_groups_idp ON authorization_groups(idp);
CREATE INDEX idx_authorization_groups_group_name ON authorization_groups(group_name);
CREATE INDEX idx_authorization_groups_last_used ON authorization_groups(last_used);

-- ============================================================================
-- CONSTRAINTS
-- ============================================================================

-- Add constraints for documents
ALTER TABLE documents ADD CONSTRAINT documents_name_not_empty
    CHECK (LENGTH(TRIM(name)) > 0);
ALTER TABLE documents ADD CONSTRAINT documents_uri_not_empty
    CHECK (LENGTH(TRIM(uri)) > 0);

-- Add constraints for notes
ALTER TABLE notes ADD CONSTRAINT notes_name_not_empty
    CHECK (LENGTH(TRIM(name)) > 0);
ALTER TABLE notes ADD CONSTRAINT notes_content_not_empty
    CHECK (LENGTH(TRIM(content)) > 0);

-- Add constraints for repositories
ALTER TABLE repositories ADD CONSTRAINT repositories_uri_not_empty
    CHECK (LENGTH(TRIM(uri)) > 0);

-- Add constraints for assets
ALTER TABLE assets ADD CONSTRAINT assets_name_not_empty
    CHECK (LENGTH(TRIM(name)) > 0);
ALTER TABLE assets ADD CONSTRAINT assets_type_not_empty
    CHECK (LENGTH(TRIM(type)) > 0);

-- Add constraints for metadata
ALTER TABLE metadata ADD CONSTRAINT metadata_key_not_empty
    CHECK (LENGTH(TRIM(key)) > 0 AND LENGTH(key) <= 128);
ALTER TABLE metadata ADD CONSTRAINT metadata_value_not_empty
    CHECK (LENGTH(TRIM(value)) > 0 AND LENGTH(value) <= 65535);
ALTER TABLE metadata ADD CONSTRAINT metadata_key_format
    CHECK (key ~ '^[a-zA-Z0-9_-]+$');

-- ============================================================================
-- FUNCTIONS AND TRIGGERS
-- ============================================================================

-- Create function to update modified_at timestamp
CREATE OR REPLACE FUNCTION update_modified_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modified_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for modified_at updates
CREATE TRIGGER update_threat_models_modified_at
    BEFORE UPDATE ON threat_models
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_diagrams_modified_at
    BEFORE UPDATE ON diagrams
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_threats_modified_at
    BEFORE UPDATE ON threats
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_threat_model_access_modified_at
    BEFORE UPDATE ON threat_model_access
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_documents_modified_at
    BEFORE UPDATE ON documents
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_notes_modified_at
    BEFORE UPDATE ON notes
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_repositories_modified_at
    BEFORE UPDATE ON repositories
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_assets_modified_at
    BEFORE UPDATE ON assets
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_metadata_modified_at
    BEFORE UPDATE ON metadata
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_webhook_subscriptions_modified_at
    BEFORE UPDATE ON webhook_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_webhook_quotas_modified_at
    BEFORE UPDATE ON webhook_quotas
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_addon_invocation_quotas_modified_at
    BEFORE UPDATE ON addon_invocation_quotas
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

CREATE TRIGGER update_user_api_quotas_modified_at
    BEFORE UPDATE ON user_api_quotas
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_at_column();

-- Create notification trigger for subscription changes (for worker wake-up)
CREATE OR REPLACE FUNCTION notify_webhook_subscription_change()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_notify('webhook_subscription_change', json_build_object(
        'operation', TG_OP,
        'subscription_id', COALESCE(NEW.id, OLD.id),
        'status', COALESCE(NEW.status, OLD.status)
    )::text);
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER webhook_subscription_change_notify
    AFTER INSERT OR UPDATE OR DELETE ON webhook_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION notify_webhook_subscription_change();

-- ============================================================================
-- SEED DATA
-- ============================================================================

-- Seed default deny list patterns for SSRF prevention
INSERT INTO webhook_url_deny_list (pattern, pattern_type, description) VALUES
    -- Localhost variants
    ('localhost', 'glob', 'Block localhost'),
    ('127.*', 'glob', 'Block loopback addresses (127.0.0.0/8)'),
    ('::1', 'glob', 'Block IPv6 loopback'),

    -- Private IPv4 ranges (RFC 1918)
    ('10.*', 'glob', 'Block private network 10.0.0.0/8'),
    ('172.16.*', 'glob', 'Block private network 172.16.0.0/12 (first subnet)'),
    ('172.17.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.18.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.19.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.20.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.21.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.22.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.23.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.24.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.25.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.26.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.27.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.28.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.29.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.30.*', 'glob', 'Block private network 172.16.0.0/12'),
    ('172.31.*', 'glob', 'Block private network 172.16.0.0/12 (last subnet)'),
    ('192.168.*', 'glob', 'Block private network 192.168.0.0/16'),

    -- Link-local addresses
    ('169.254.*', 'glob', 'Block link-local addresses (169.254.0.0/16)'),
    ('fe80:*', 'glob', 'Block IPv6 link-local addresses (fe80::/10)'),

    -- Private IPv6 ranges
    ('fc00:*', 'glob', 'Block IPv6 unique local addresses (fc00::/7)'),
    ('fd00:*', 'glob', 'Block IPv6 unique local addresses (fd00::/8)'),

    -- Cloud metadata endpoints
    ('169.254.169.254', 'glob', 'Block AWS/Azure/GCP metadata service'),
    ('fd00:ec2::254', 'glob', 'Block AWS IMDSv2 IPv6 metadata service'),
    ('metadata.google.internal', 'glob', 'Block GCP metadata service'),
    ('169.254.169.123', 'glob', 'Block DigitalOcean metadata service'),

    -- Kubernetes internal services
    ('kubernetes.default.svc', 'glob', 'Block Kubernetes internal service'),
    ('10.96.0.*', 'glob', 'Block common Kubernetes service CIDR'),

    -- Docker internal network
    ('172.17.0.1', 'glob', 'Block Docker default bridge gateway'),

    -- Broadcast addresses
    ('255.255.255.255', 'glob', 'Block broadcast address'),
    ('0.0.0.0', 'glob', 'Block null address')
ON CONFLICT DO NOTHING;

-- Add comment explaining severity field flexibility
COMMENT ON COLUMN threats.severity IS
  'Severity level - accepts numeric strings (0-5), standard values (Unknown, None, Low, Medium, High, Critical), custom values, or localized strings. Supports Unicode characters, alphanumeric, hyphens, underscores, parentheses, periods. Maximum 50 characters.';
