package config

import (
	"os"
	"strings"
	"testing"
)

func TestGenerateExampleConfig_ContainsBootstrapKeys(t *testing.T) {
	out, err := GenerateExampleConfig()
	if err != nil {
		t.Fatalf("GenerateExampleConfig: %v", err)
	}
	s := string(out)
	for _, want := range []string{"database:", "server:", "logging:"} {
		if !strings.Contains(s, want) {
			t.Errorf("generated example missing %q", want)
		}
	}
}

func TestGenerateExampleConfig_OmitsOperationalKeys(t *testing.T) {
	out, err := GenerateExampleConfig()
	if err != nil {
		t.Fatalf("GenerateExampleConfig: %v", err)
	}
	if strings.Contains(string(out), "inactivity_timeout_seconds") {
		t.Error("generated example should not contain operational keys")
	}
}

func TestConfigExampleFile_MatchesRegistry(t *testing.T) {
	generated, err := GenerateExampleConfig()
	if err != nil {
		t.Fatalf("GenerateExampleConfig: %v", err)
	}
	onDisk, err := os.ReadFile("../../config-example.yml")
	if err != nil {
		t.Fatalf("read config-example.yml: %v", err)
	}
	strip := func(b []byte) string {
		var keep []string
		for _, line := range strings.Split(string(b), "\n") {
			if strings.Contains(line, "GENERATED by") {
				continue
			}
			keep = append(keep, line)
		}
		return strings.Join(keep, "\n")
	}
	if strip(generated) != strip(onDisk) {
		t.Error("config-example.yml is stale — run `make generate-config-example`")
	}
}
