package config

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// GenerateExampleConfig produces the contents of config-example.yml from the
// classification registry. Only CategoryBootstrap keys are included — the
// example file documents the bootstrap-only config, since operational config
// lives in the database. Secret values are emitted as reference placeholders.
// SEM@a60b4f430769f6d36f0e3753a429ea699ba8b1a0: build annotated example YAML for bootstrap-only config keys with vault placeholders for secrets (pure)
func GenerateExampleConfig() ([]byte, error) {
	cfg := getDefaultConfig()
	cfg.Server.TLSSubjectName = "localhost" // pin to a deterministic value — the example file must not embed the build host's name
	all := cfg.GetMigratableSettings()

	bootstrap := make([]MigratableSetting, 0, len(all))
	for _, s := range all {
		if s.Class.Category == CategoryBootstrap {
			bootstrap = append(bootstrap, s)
		}
	}
	sort.Slice(bootstrap, func(i, j int) bool { return bootstrap[i].Key < bootstrap[j].Key })

	root := map[string]any{}
	for _, s := range bootstrap {
		var value any
		if s.Class.Secret {
			value = "vault://replace-me/" + strings.ReplaceAll(s.Key, ".", "/")
		} else {
			value = coerceSettingValue(s)
		}
		setNested(root, strings.Split(s.Key, "."), value)
	}

	header := fmt.Sprintf(
		"# TMI Example Configuration (bootstrap keys only)\n"+
			"# GENERATED by `make generate-config-example` on %s — do not edit by hand.\n"+
			"# Operational and shared configuration lives in the database settings service.\n"+
			"# Secret values are shown as vault:// reference placeholders.\n\n",
		time.Now().UTC().Format(time.RFC3339))

	body, err := yaml.Marshal(root)
	if err != nil {
		return nil, fmt.Errorf("marshal example config: %w", err)
	}
	return append([]byte(header), body...), nil
}

// coerceSettingValue converts a MigratableSetting's string Value to the
// appropriate Go type based on the Type field, so that yaml.Marshal outputs
// clean YAML (integers without quotes, booleans as true/false, etc.).
// SEM@e6cee63c3a07d38f471e0ebfb81722849f36085e: convert a migratable setting's string value to its typed Go representation for YAML output (pure)
func coerceSettingValue(s MigratableSetting) any {
	switch s.Type {
	case "int":
		if i, err := strconv.Atoi(s.Value); err == nil {
			return i
		}
	case "bool":
		if b, err := strconv.ParseBool(s.Value); err == nil {
			return b
		}
	case "float":
		if f, err := strconv.ParseFloat(s.Value, 64); err == nil {
			return f
		}
	case "json":
		return coerceJSONSettingValue(s.Value)
	}
	// Default: return as string (handles "string", duration strings, etc.)
	return s.Value
}

// coerceJSONSettingValue decodes a "json"-typed setting's already-marshaled
// string into a native Go value, so yaml.Marshal renders it as a real YAML
// list/mapping rather than dumping the JSON text as a quoted string.
//
// A nil Go slice (e.g. an unset []string field) marshals to the JSON string
// "null"; without this decoding step that string flows through unchanged and
// yaml.Marshal writes the literal YAML string `"null"`, which is not valid
// YAML for a list-typed key. An explicitly-empty JSON array ("[]") has the
// same problem in miniature: it would otherwise round-trip as the string
// "[]" rather than an empty list. Both cases are normalized to an empty Go
// slice here, which yaml.Marshal renders as `[]` — matching the convention
// this file already uses for empty collections (server.cors.allowed_origins
// is omitted outright via OmitWhenEmpty when empty; a setting that is
// deliberately not OmitWhenEmpty, like server.trusted_proxies, still needs a
// valid, honest empty-list rendering when its default is unset).
// SEM@e6cee63c3a07d38f471e0ebfb81722849f36085e: decode a JSON-typed setting's string value into a native Go value for YAML (pure)
func coerceJSONSettingValue(value string) any {
	if value == "" || value == "null" || value == "[]" {
		return []any{}
	}
	var decoded any
	if err := json.Unmarshal([]byte(value), &decoded); err == nil {
		return decoded
	}
	// Malformed JSON should not happen (the value came from json.Marshal in
	// the setting's own Get accessor); fall back to the raw string rather
	// than panicking or silently dropping the key.
	return value
}

// setNested writes value into a nested map following the dotted key path.
// SEM@a60b4f430769f6d36f0e3753a429ea699ba8b1a0: write a value into a nested map following a dotted key path (mutates shared state)
func setNested(root map[string]any, path []string, value any) {
	cur := root
	for i, part := range path {
		if i == len(path)-1 {
			cur[part] = value
			return
		}
		next, ok := cur[part].(map[string]any)
		if !ok {
			if _, exists := cur[part]; exists {
				panic(fmt.Sprintf("setNested: config key path collision at %q", strings.Join(path[:i+1], ".")))
			}
			next = map[string]any{}
			cur[part] = next
		}
		cur = next
	}
}
