package config

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// GenerateReferenceMarkdown produces the per-key configuration reference from
// the classification registry. It emits two tables — bootstrap and operational
// — so the wiki Configuration-Reference page is generated, not hand-maintained.
// Secret defaults are shown as vault:// placeholders, never real values.
// SEM@15870ed6c51c35dd0b30cf6f7a777a7010b1b69e: build the wiki configuration reference as Markdown with bootstrap and operational tables (pure)
func GenerateReferenceMarkdown() ([]byte, error) {
	cfg := getDefaultConfig()
	cfg.Server.TLSSubjectName = "localhost" // deterministic — must not embed the build host's name
	all := cfg.GetMigratableSettings()

	var bootstrap, operational []MigratableSetting
	for _, s := range all {
		switch s.Class.Category {
		case CategoryBootstrap:
			bootstrap = append(bootstrap, s)
		case CategoryOperational:
			operational = append(operational, s)
		}
	}
	sort.Slice(bootstrap, func(i, j int) bool { return bootstrap[i].Key < bootstrap[j].Key })
	sort.Slice(operational, func(i, j int) bool { return operational[i].Key < operational[j].Key })

	var b strings.Builder
	fmt.Fprintf(&b,
		"# Configuration Reference\n\n"+
			"<!-- GENERATED by `make generate-config-docs` on %s — do not edit by hand. -->\n\n"+
			"Every TMI configuration key, grouped by category. See "+
			"[[Configuration-Model]] for what the categories and columns mean.\n\n",
		time.Now().UTC().Format(time.RFC3339))

	b.WriteString("## Bootstrap settings\n\n")
	b.WriteString("File/env only, read once at startup. Cannot come from the database.\n\n")
	b.WriteString("| Key | Env var | Type | Default | Required | Secret | Description |\n")
	b.WriteString("|-----|---------|------|---------|----------|--------|-------------|\n")
	for _, s := range bootstrap {
		b.WriteString(bootstrapRow(s))
	}

	b.WriteString("\n## Operational settings\n\n")
	b.WriteString("DB-backed, seeded from defaults on first run, editable at runtime via `/admin/settings`.\n\n")
	b.WriteString("| Key | Type | Default | Mutability | Visibility | Secret | Description |\n")
	b.WriteString("|-----|------|---------|------------|------------|--------|-------------|\n")
	for _, s := range operational {
		b.WriteString(operationalRow(s))
	}

	return []byte(b.String()), nil
}

// SEM@15870ed6c51c35dd0b30cf6f7a777a7010b1b69e: format a bootstrap config setting as a Markdown table row (pure)
func bootstrapRow(s MigratableSetting) string {
	return fmt.Sprintf("| `%s` | %s | %s | %s | %s | %s | %s |\n",
		s.Key, codeOrDash(s.EnvVar), s.Type, defaultCell(s),
		yesNo(s.Class.Required), yesNo(s.Class.Secret), sanitizeCell(s.Description))
}

// SEM@15870ed6c51c35dd0b30cf6f7a777a7010b1b69e: format an operational config setting as a Markdown table row (pure)
func operationalRow(s MigratableSetting) string {
	return fmt.Sprintf("| `%s` | %s | %s | %s | %s | %s | %s |\n",
		s.Key, s.Type, defaultCell(s), s.Class.Mutability.String(),
		s.Class.Visibility.String(), yesNo(s.Class.Secret), sanitizeCell(s.Description))
}

// SEM@15870ed6c51c35dd0b30cf6f7a777a7010b1b69e: format a config setting's default value, masking secrets as placeholder (pure)
func defaultCell(s MigratableSetting) string {
	if s.Class.Secret {
		return "_(secret)_"
	}
	if s.Value == "" {
		return "_(none)_"
	}
	return "`" + sanitizeCell(s.Value) + "`"
}

// SEM@15870ed6c51c35dd0b30cf6f7a777a7010b1b69e: format a string as inline code or an em-dash when empty (pure)
func codeOrDash(v string) string {
	if v == "" {
		return "—"
	}
	return "`" + v + "`"
}

// SEM@15870ed6c51c35dd0b30cf6f7a777a7010b1b69e: convert a boolean to 'yes' or 'no' (pure)
func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

// SEM@15870ed6c51c35dd0b30cf6f7a777a7010b1b69e: escape Markdown table-breaking characters in a config cell value (pure)
func sanitizeCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "`", "'")
	return s
}
