package config

import (
	"os"
	"strings"
	"testing"
)

func TestGenerateReferenceMarkdown_HasBothCategoryTables(t *testing.T) {
	out, err := GenerateReferenceMarkdown()
	if err != nil {
		t.Fatalf("GenerateReferenceMarkdown: %v", err)
	}
	s := string(out)
	for _, want := range []string{"## Bootstrap settings", "## Operational settings"} {
		if !strings.Contains(s, want) {
			t.Errorf("reference missing section %q", want)
		}
	}
}

func TestGenerateReferenceMarkdown_BootstrapKeyHasEnvVar(t *testing.T) {
	out, err := GenerateReferenceMarkdown()
	if err != nil {
		t.Fatalf("GenerateReferenceMarkdown: %v", err)
	}
	// server.port is bootstrap and overridable by TMI_SERVER_PORT.
	if !strings.Contains(string(out), "`TMI_SERVER_PORT`") {
		t.Error("reference missing env var TMI_SERVER_PORT for server.port")
	}
}

func TestGenerateReferenceMarkdown_NeverLeaksSecretDefault(t *testing.T) {
	out, err := GenerateReferenceMarkdown()
	if err != nil {
		t.Fatalf("GenerateReferenceMarkdown: %v", err)
	}
	s := string(out)
	cfg := getDefaultConfig()
	for _, ms := range cfg.GetMigratableSettings() {
		if !ms.Class.Secret {
			continue
		}
		// A secret's real default value must never appear in the reference.
		if ms.Value != "" && strings.Contains(s, "`"+ms.Value+"`") {
			t.Errorf("secret %q default value leaked into reference", ms.Key)
		}
		// Its row must render the masked placeholder.
		for _, line := range strings.Split(s, "\n") {
			if strings.Contains(line, "`"+ms.Key+"`") && !strings.Contains(line, "_(secret)_") {
				t.Errorf("secret %q row not masked: %q", ms.Key, line)
			}
		}
	}
}

func TestGenerateReferenceMarkdown_HasPrecedenceSection(t *testing.T) {
	out, err := GenerateReferenceMarkdown()
	if err != nil {
		t.Fatalf("GenerateReferenceMarkdown: %v", err)
	}
	s := string(out)
	for _, want := range []string{
		"## Precedence",
		"config explicit",
		"DB explicit",
		"auth.oauth.providers.*",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("reference missing precedence prose %q", want)
		}
	}
}

func TestGenerateReferenceMarkdown_PrecedenceColumnByCategory(t *testing.T) {
	out, err := GenerateReferenceMarkdown()
	if err != nil {
		t.Fatalf("GenerateReferenceMarkdown: %v", err)
	}
	s := string(out)

	// server.port is bootstrap: config/env only, never DB-backed.
	bootstrapLine := findRowContaining(t, s, "`server.port`")
	if !strings.Contains(bootstrapLine, "config/env only") {
		t.Errorf("bootstrap key server.port: want precedence cell %q, got row %q", "config/env only", bootstrapLine)
	}

	// auth.auto_promote_first_user is operational: DB wins unless config is explicit.
	operationalLine := findRowContaining(t, s, "`auth.auto_promote_first_user`")
	if !strings.Contains(operationalLine, "db unless config explicit") {
		t.Errorf("operational key auth.auto_promote_first_user: want precedence cell %q, got row %q",
			"db unless config explicit", operationalLine)
	}
}

func findRowContaining(t *testing.T, doc, keyCell string) string {
	t.Helper()
	for _, line := range strings.Split(doc, "\n") {
		if strings.Contains(line, keyCell) {
			return line
		}
	}
	t.Fatalf("no table row found containing %q", keyCell)
	return ""
}

func TestConfigReferenceFile_MatchesRegistry(t *testing.T) {
	generated, err := GenerateReferenceMarkdown()
	if err != nil {
		t.Fatalf("GenerateReferenceMarkdown: %v", err)
	}
	onDisk, err := os.ReadFile("../../config-reference.md")
	if err != nil {
		t.Fatalf("read config-reference.md: %v", err)
	}
	strip := func(b []byte) string {
		var keep []string
		for _, line := range strings.Split(string(b), "\n") {
			if strings.Contains(line, "GENERATED by") {
				continue
			}
			keep = append(keep, line)
		}
		return strings.Join(keep, "\n")
	}
	if strip(generated) != strip(onDisk) {
		t.Error("config-reference.md is stale — run `make generate-config-docs`")
	}
}
