package config

import "strconv"

// contentSettingDefs declares the Timmy and content-pipeline settings:
// timmy.*, content_extractors.* (including its extraction.async_enabled
// rename), content_oauth.callback_url, content_sources.*, and the top-level
// content_token_encryption_key. Per-provider content_oauth.providers.<id>.*
// keys are generated at runtime per configured provider and have no static
// SettingDef — see prefixClassifications in classification_registry.go.
var contentSettingDefs = []SettingDef{
	// --- Timmy: LLM chat ---
	// timmy.enabled is the one Timmy key that stays Hot: cmd/server/main.go's
	// cfgReader closure (feeding the runtime-swappable ContentSourceHolder)
	// explicitly overlays it from settingsService.GetBool(ctx, "timmy.enabled")
	// on every rebuild, on top of an otherwise-static *cfg snapshot — see that
	// closure's own comment, "the live config reader snapshots *cfg ... then
	// overlays timmy.enabled from the settings service". Every other Timmy
	// key below (and every content_extractors.*/content_sources.*/
	// content_oauth.callback_url key later in this file) is read only from
	// that static snapshot, which the same comment calls out directly:
	// "most content-source fields live in the static config" — so they are
	// Static, and each such def is wrapped in withMutability(..., MutabilityStatic)
	// rather than repeating this comment at every entry.
	{
		Key:          "timmy.enabled",
		Class:        classificationFor("timmy.enabled"),
		Type:         "bool",
		Description:  "Timmy AI assistant enabled",
		Default:      "false",
		YAMLPath:     "timmy.enabled",
		EnvVar:       "TMI_TIMMY_ENABLED",
		Get:          func(c *Config) string { return strconv.FormatBool(c.Timmy.Enabled) },
		Transitional: true,
	},
	{
		Key:          "timmy.llm_provider",
		Class:        withMutability(classificationFor("timmy.llm_provider"), MutabilityStatic),
		Type:         "string",
		Description:  "LLM provider",
		Default:      "",
		YAMLPath:     "timmy.llm_provider",
		EnvVar:       "TMI_TIMMY_LLM_PROVIDER",
		Get:          func(c *Config) string { return c.Timmy.LLMProvider },
		Transitional: true,
	},
	{
		Key:          "timmy.llm_model",
		Class:        withMutability(classificationFor("timmy.llm_model"), MutabilityStatic),
		Type:         "string",
		Description:  "LLM model",
		Default:      "",
		YAMLPath:     "timmy.llm_model",
		EnvVar:       "TMI_TIMMY_LLM_MODEL",
		Get:          func(c *Config) string { return c.Timmy.LLMModel },
		Transitional: true,
	},
	{
		Key:          "timmy.llm_api_key",
		Class:        withMutability(classificationFor("timmy.llm_api_key"), MutabilityStatic),
		Type:         "string",
		Description:  "LLM API key",
		Default:      "",
		YAMLPath:     "timmy.llm_api_key",
		EnvVar:       "TMI_TIMMY_LLM_API_KEY",
		Get:          func(c *Config) string { return c.Timmy.LLMAPIKey },
		Transitional: true,
	},
	{
		Key:          "timmy.llm_base_url",
		Class:        withMutability(classificationFor("timmy.llm_base_url"), MutabilityStatic),
		Type:         "string",
		Description:  "LLM API base URL",
		Default:      "",
		YAMLPath:     "timmy.llm_base_url",
		EnvVar:       "TMI_TIMMY_LLM_BASE_URL",
		Get:          func(c *Config) string { return c.Timmy.LLMBaseURL },
		Transitional: true,
	},
	{
		Key:          "timmy.llm_max_tokens",
		Class:        withMutability(classificationFor("timmy.llm_max_tokens"), MutabilityStatic),
		Type:         "int",
		Description:  "Max tokens per chat completion (required by Anthropic; optional for OpenAI)",
		Default:      "4096",
		YAMLPath:     "timmy.llm_max_tokens",
		EnvVar:       "TMI_TIMMY_LLM_MAX_TOKENS",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.LLMMaxTokens) },
		Transitional: true,
	},

	// --- Timmy: text embedding profile (shared invariant between ingest and query) ---
	{
		Key:          "timmy.text_embedding_provider",
		Class:        withMutability(classificationFor("timmy.text_embedding_provider"), MutabilityStatic),
		Type:         "string",
		Description:  "Text embedding provider",
		Default:      "",
		YAMLPath:     "timmy.text_embedding_provider",
		EnvVar:       "TMI_TIMMY_TEXT_EMBEDDING_PROVIDER",
		Get:          func(c *Config) string { return c.Timmy.TextEmbeddingProvider },
		Transitional: true,
	},
	{
		Key:          "timmy.text_embedding_model",
		Class:        withMutability(classificationFor("timmy.text_embedding_model"), MutabilityStatic),
		Type:         "string",
		Description:  "Text embedding model — shared invariant between ingest and query",
		Default:      "",
		YAMLPath:     "timmy.text_embedding_model",
		EnvVar:       "TMI_TIMMY_TEXT_EMBEDDING_MODEL",
		Get:          func(c *Config) string { return c.Timmy.TextEmbeddingModel },
		Transitional: true,
	},
	{
		Key:          "timmy.text_embedding_api_key",
		Class:        withMutability(classificationFor("timmy.text_embedding_api_key"), MutabilityStatic),
		Type:         "string",
		Description:  "Text embedding API key",
		Default:      "",
		YAMLPath:     "timmy.text_embedding_api_key",
		EnvVar:       "TMI_TIMMY_TEXT_EMBEDDING_API_KEY",
		Get:          func(c *Config) string { return c.Timmy.TextEmbeddingAPIKey },
		Transitional: true,
	},
	{
		Key:          "timmy.text_embedding_base_url",
		Class:        withMutability(classificationFor("timmy.text_embedding_base_url"), MutabilityStatic),
		Type:         "string",
		Description:  "Text embedding API base URL — shared invariant",
		Default:      "",
		YAMLPath:     "timmy.text_embedding_base_url",
		EnvVar:       "TMI_TIMMY_TEXT_EMBEDDING_BASE_URL",
		Get:          func(c *Config) string { return c.Timmy.TextEmbeddingBaseURL },
		Transitional: true,
	},
	{
		Key:          "timmy.embedding_dimension",
		Class:        withMutability(classificationFor("timmy.embedding_dimension"), MutabilityStatic),
		Type:         "int",
		Description:  "Text embedding vector dimension — shared invariant",
		Default:      "0",
		YAMLPath:     "timmy.embedding_dimension",
		EnvVar:       "TMI_TIMMY_EMBEDDING_DIMENSION",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.EmbeddingDimension) },
		Transitional: true,
	},
	{
		Key:          "timmy.text_retrieval_top_k",
		Class:        withMutability(classificationFor("timmy.text_retrieval_top_k"), MutabilityStatic),
		Type:         "int",
		Description:  "Text retrieval top-k results",
		Default:      "10",
		YAMLPath:     "timmy.text_retrieval_top_k",
		EnvVar:       "TMI_TIMMY_TEXT_RETRIEVAL_TOP_K",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.TextRetrievalTopK) },
		Transitional: true,
	},

	// --- Timmy: code embedding profile ---
	{
		Key:          "timmy.code_embedding_provider",
		Class:        withMutability(classificationFor("timmy.code_embedding_provider"), MutabilityStatic),
		Type:         "string",
		Description:  "Code embedding provider",
		Default:      "",
		YAMLPath:     "timmy.code_embedding_provider",
		EnvVar:       "TMI_TIMMY_CODE_EMBEDDING_PROVIDER",
		Get:          func(c *Config) string { return c.Timmy.CodeEmbeddingProvider },
		Transitional: true,
	},
	{
		Key:          "timmy.code_embedding_model",
		Class:        withMutability(classificationFor("timmy.code_embedding_model"), MutabilityStatic),
		Type:         "string",
		Description:  "Code embedding model",
		Default:      "",
		YAMLPath:     "timmy.code_embedding_model",
		EnvVar:       "TMI_TIMMY_CODE_EMBEDDING_MODEL",
		Get:          func(c *Config) string { return c.Timmy.CodeEmbeddingModel },
		Transitional: true,
	},
	{
		Key:          "timmy.code_embedding_api_key",
		Class:        withMutability(classificationFor("timmy.code_embedding_api_key"), MutabilityStatic),
		Type:         "string",
		Description:  "Code embedding API key",
		Default:      "",
		YAMLPath:     "timmy.code_embedding_api_key",
		EnvVar:       "TMI_TIMMY_CODE_EMBEDDING_API_KEY",
		Get:          func(c *Config) string { return c.Timmy.CodeEmbeddingAPIKey },
		Transitional: true,
	},
	{
		Key:          "timmy.code_embedding_base_url",
		Class:        withMutability(classificationFor("timmy.code_embedding_base_url"), MutabilityStatic),
		Type:         "string",
		Description:  "Code embedding API base URL",
		Default:      "",
		YAMLPath:     "timmy.code_embedding_base_url",
		EnvVar:       "TMI_TIMMY_CODE_EMBEDDING_BASE_URL",
		Get:          func(c *Config) string { return c.Timmy.CodeEmbeddingBaseURL },
		Transitional: true,
	},
	{
		Key:          "timmy.code_retrieval_top_k",
		Class:        withMutability(classificationFor("timmy.code_retrieval_top_k"), MutabilityStatic),
		Type:         "int",
		Description:  "Code retrieval top-k results",
		Default:      "10",
		YAMLPath:     "timmy.code_retrieval_top_k",
		EnvVar:       "TMI_TIMMY_CODE_RETRIEVAL_TOP_K",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.CodeRetrievalTopK) },
		Transitional: true,
	},
	{
		Key:          "timmy.query_decomposition_enabled",
		Class:        withMutability(classificationFor("timmy.query_decomposition_enabled"), MutabilityStatic),
		Type:         "bool",
		Description:  "Query decomposition enabled",
		Default:      "false",
		YAMLPath:     "timmy.query_decomposition_enabled",
		EnvVar:       "TMI_TIMMY_QUERY_DECOMPOSITION_ENABLED",
		Get:          func(c *Config) string { return strconv.FormatBool(c.Timmy.QueryDecompositionEnabled) },
		Transitional: true,
	},

	// --- Timmy: reranker ---
	{
		Key:          "timmy.rerank_provider",
		Class:        withMutability(classificationFor("timmy.rerank_provider"), MutabilityStatic),
		Type:         "string",
		Description:  "Reranker provider",
		Default:      "",
		YAMLPath:     "timmy.rerank_provider",
		EnvVar:       "TMI_TIMMY_RERANK_PROVIDER",
		Get:          func(c *Config) string { return c.Timmy.RerankProvider },
		Transitional: true,
	},
	{
		Key:          "timmy.rerank_model",
		Class:        withMutability(classificationFor("timmy.rerank_model"), MutabilityStatic),
		Type:         "string",
		Description:  "Reranker model",
		Default:      "",
		YAMLPath:     "timmy.rerank_model",
		EnvVar:       "TMI_TIMMY_RERANK_MODEL",
		Get:          func(c *Config) string { return c.Timmy.RerankModel },
		Transitional: true,
	},
	{
		Key:          "timmy.rerank_api_key",
		Class:        withMutability(classificationFor("timmy.rerank_api_key"), MutabilityStatic),
		Type:         "string",
		Description:  "Reranker API key",
		Default:      "",
		YAMLPath:     "timmy.rerank_api_key",
		EnvVar:       "TMI_TIMMY_RERANK_API_KEY",
		Get:          func(c *Config) string { return c.Timmy.RerankAPIKey },
		Transitional: true,
	},
	{
		Key:          "timmy.rerank_base_url",
		Class:        withMutability(classificationFor("timmy.rerank_base_url"), MutabilityStatic),
		Type:         "string",
		Description:  "Reranker API base URL",
		Default:      "",
		YAMLPath:     "timmy.rerank_base_url",
		EnvVar:       "TMI_TIMMY_RERANK_BASE_URL",
		Get:          func(c *Config) string { return c.Timmy.RerankBaseURL },
		Transitional: true,
	},
	{
		Key:          "timmy.rerank_top_k",
		Class:        withMutability(classificationFor("timmy.rerank_top_k"), MutabilityStatic),
		Type:         "int",
		Description:  "Reranker top-k results",
		Default:      "10",
		YAMLPath:     "timmy.rerank_top_k",
		EnvVar:       "TMI_TIMMY_RERANK_TOP_K",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.RerankTopK) },
		Transitional: true,
	},

	// --- Timmy: session / resource limits ---
	{
		Key:          "timmy.max_conversation_history",
		Class:        withMutability(classificationFor("timmy.max_conversation_history"), MutabilityStatic),
		Type:         "int",
		Description:  "Max conversation history entries",
		Default:      "50",
		YAMLPath:     "timmy.max_conversation_history",
		EnvVar:       "TMI_TIMMY_MAX_CONVERSATION_HISTORY",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.MaxConversationHistory) },
		Transitional: true,
	},
	{
		Key:          "timmy.operator_system_prompt",
		Class:        withMutability(classificationFor("timmy.operator_system_prompt"), MutabilityStatic),
		Type:         "string",
		Description:  "Operator system prompt override",
		Default:      "",
		YAMLPath:     "timmy.operator_system_prompt",
		EnvVar:       "TMI_TIMMY_OPERATOR_SYSTEM_PROMPT",
		Get:          func(c *Config) string { return c.Timmy.OperatorSystemPrompt },
		Transitional: true,
	},
	{
		Key:          "timmy.max_memory_mb",
		Class:        withMutability(classificationFor("timmy.max_memory_mb"), MutabilityStatic),
		Type:         "int",
		Description:  "Max memory in MB",
		Default:      "256",
		YAMLPath:     "timmy.max_memory_mb",
		EnvVar:       "TMI_TIMMY_MAX_MEMORY_MB",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.MaxMemoryMB) },
		Transitional: true,
	},
	{
		Key:          "timmy.inactivity_timeout_seconds",
		Class:        withMutability(classificationFor("timmy.inactivity_timeout_seconds"), MutabilityStatic),
		Type:         "int",
		Description:  "Session inactivity timeout in seconds",
		Default:      "3600",
		YAMLPath:     "timmy.inactivity_timeout_seconds",
		EnvVar:       "TMI_TIMMY_INACTIVITY_TIMEOUT_SECONDS",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.InactivityTimeoutSeconds) },
		Transitional: true,
	},
	{
		Key:          "timmy.max_messages_per_user_per_hour",
		Class:        withMutability(classificationFor("timmy.max_messages_per_user_per_hour"), MutabilityStatic),
		Type:         "int",
		Description:  "Max messages per user per hour",
		Default:      "60",
		YAMLPath:     "timmy.max_messages_per_user_per_hour",
		EnvVar:       "TMI_TIMMY_MAX_MESSAGES_PER_USER_PER_HOUR",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.MaxMessagesPerUserPerHour) },
		Transitional: true,
	},
	{
		Key:          "timmy.max_sessions_per_threat_model",
		Class:        withMutability(classificationFor("timmy.max_sessions_per_threat_model"), MutabilityStatic),
		Type:         "int",
		Description:  "Max Timmy sessions per threat model",
		Default:      "50",
		YAMLPath:     "timmy.max_sessions_per_threat_model",
		EnvVar:       "TMI_TIMMY_MAX_SESSIONS_PER_THREAT_MODEL",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.MaxSessionsPerThreatModel) },
		Transitional: true,
	},
	{
		Key:          "timmy.max_concurrent_llm_requests",
		Class:        withMutability(classificationFor("timmy.max_concurrent_llm_requests"), MutabilityStatic),
		Type:         "int",
		Description:  "Max concurrent LLM requests",
		Default:      "10",
		YAMLPath:     "timmy.max_concurrent_llm_requests",
		EnvVar:       "TMI_TIMMY_MAX_CONCURRENT_LLM_REQUESTS",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.MaxConcurrentLLMRequests) },
		Transitional: true,
	},

	// --- Timmy: chunking / embedding lifecycle ---
	{
		Key:          "timmy.chunk_size",
		Class:        withMutability(classificationFor("timmy.chunk_size"), MutabilityStatic),
		Type:         "int",
		Description:  "Embedding chunk size",
		Default:      "512",
		YAMLPath:     "timmy.chunk_size",
		EnvVar:       "TMI_TIMMY_CHUNK_SIZE",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.ChunkSize) },
		Transitional: true,
	},
	{
		Key:          "timmy.chunk_overlap",
		Class:        withMutability(classificationFor("timmy.chunk_overlap"), MutabilityStatic),
		Type:         "int",
		Description:  "Embedding chunk overlap",
		Default:      "50",
		YAMLPath:     "timmy.chunk_overlap",
		EnvVar:       "TMI_TIMMY_CHUNK_OVERLAP",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.ChunkOverlap) },
		Transitional: true,
	},
	{
		Key:          "timmy.llm_timeout_seconds",
		Class:        withMutability(classificationFor("timmy.llm_timeout_seconds"), MutabilityStatic),
		Type:         "int",
		Description:  "LLM request timeout in seconds",
		Default:      "120",
		YAMLPath:     "timmy.llm_timeout_seconds",
		EnvVar:       "TMI_TIMMY_LLM_TIMEOUT_SECONDS",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.LLMTimeoutSeconds) },
		Transitional: true,
	},
	{
		Key:          "timmy.embedding_cleanup_interval_minutes",
		Class:        withMutability(classificationFor("timmy.embedding_cleanup_interval_minutes"), MutabilityStatic),
		Type:         "int",
		Description:  "Embedding cleanup interval in minutes",
		Default:      "60",
		YAMLPath:     "timmy.embedding_cleanup_interval_minutes",
		EnvVar:       "TMI_TIMMY_EMBEDDING_CLEANUP_INTERVAL_MINUTES",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.EmbeddingCleanupIntervalMinutes) },
		Transitional: true,
	},
	{
		Key:          "timmy.embedding_idle_days_active",
		Class:        withMutability(classificationFor("timmy.embedding_idle_days_active"), MutabilityStatic),
		Type:         "int",
		Description:  "Days before idle active-TM embeddings are cleaned up",
		Default:      "30",
		YAMLPath:     "timmy.embedding_idle_days_active",
		EnvVar:       "TMI_TIMMY_EMBEDDING_IDLE_DAYS_ACTIVE",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.EmbeddingIdleDaysActive) },
		Transitional: true,
	},
	{
		Key:          "timmy.embedding_idle_days_closed",
		Class:        withMutability(classificationFor("timmy.embedding_idle_days_closed"), MutabilityStatic),
		Type:         "int",
		Description:  "Days before idle closed-TM embeddings are cleaned up",
		Default:      "7",
		YAMLPath:     "timmy.embedding_idle_days_closed",
		EnvVar:       "TMI_TIMMY_EMBEDDING_IDLE_DAYS_CLOSED",
		Get:          func(c *Config) string { return strconv.Itoa(c.Timmy.EmbeddingIdleDaysClosed) },
		Transitional: true,
	},
	{
		Key:          "timmy.dump_extracted_text_to_note",
		Class:        withMutability(classificationFor("timmy.dump_extracted_text_to_note"), MutabilityStatic),
		Type:         "bool",
		Description:  "Dump extracted text to note (dev/test only)",
		Default:      "false",
		YAMLPath:     "timmy.dump_extracted_text_to_note",
		EnvVar:       "TMI_TIMMY_DUMP_EXTRACTED_TEXT_TO_NOTE",
		Get:          func(c *Config) string { return strconv.FormatBool(c.Timmy.DumpExtractedTextToNote) },
		Transitional: true,
	},

	// --- Content extractors: OOXML pipeline limits ---
	{
		Key:          "content_extractors.compressed_size_bytes",
		Class:        withMutability(classificationFor("content_extractors.compressed_size_bytes"), MutabilityStatic),
		Type:         "int",
		Description:  "Max compressed upload size in bytes",
		Default:      "20971520",
		YAMLPath:     "content_extractors.compressed_size_bytes",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_COMPRESSED_SIZE_BYTES",
		Get:          func(c *Config) string { return strconv.FormatInt(c.ContentExtractors.CompressedSizeBytes, 10) },
		Transitional: true,
	},
	{
		Key:          "content_extractors.decompressed_size_bytes",
		Class:        withMutability(classificationFor("content_extractors.decompressed_size_bytes"), MutabilityStatic),
		Type:         "int",
		Description:  "Max decompressed content size in bytes",
		Default:      "52428800",
		YAMLPath:     "content_extractors.decompressed_size_bytes",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_DECOMPRESSED_SIZE_BYTES",
		Get:          func(c *Config) string { return strconv.FormatInt(c.ContentExtractors.DecompressedSizeBytes, 10) },
		Transitional: true,
	},
	{
		Key:          "content_extractors.part_size_bytes",
		Class:        withMutability(classificationFor("content_extractors.part_size_bytes"), MutabilityStatic),
		Type:         "int",
		Description:  "Max size of a single archive part in bytes",
		Default:      "20971520",
		YAMLPath:     "content_extractors.part_size_bytes",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_PART_SIZE_BYTES",
		Get:          func(c *Config) string { return strconv.FormatInt(c.ContentExtractors.PartSizeBytes, 10) },
		Transitional: true,
	},
	{
		Key:          "content_extractors.pptx_slides",
		Class:        withMutability(classificationFor("content_extractors.pptx_slides"), MutabilityStatic),
		Type:         "int",
		Description:  "Max number of PowerPoint slides to extract",
		Default:      "100",
		YAMLPath:     "content_extractors.pptx_slides",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_PPTX_SLIDES",
		Get:          func(c *Config) string { return strconv.Itoa(c.ContentExtractors.PPTXSlides) },
		Transitional: true,
	},
	{
		Key:          "content_extractors.xlsx_cells",
		Class:        withMutability(classificationFor("content_extractors.xlsx_cells"), MutabilityStatic),
		Type:         "int",
		Description:  "Max number of Excel cells to extract",
		Default:      "1000",
		YAMLPath:     "content_extractors.xlsx_cells",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_XLSX_CELLS",
		Get:          func(c *Config) string { return strconv.Itoa(c.ContentExtractors.XLSXCells) },
		Transitional: true,
	},
	{
		Key:          "content_extractors.markdown_size_bytes",
		Class:        withMutability(classificationFor("content_extractors.markdown_size_bytes"), MutabilityStatic),
		Type:         "int",
		Description:  "Max markdown output size in bytes",
		Default:      "131072",
		YAMLPath:     "content_extractors.markdown_size_bytes",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_MARKDOWN_SIZE_BYTES",
		Get:          func(c *Config) string { return strconv.FormatInt(c.ContentExtractors.MarkdownSizeBytes, 10) },
		Transitional: true,
	},
	{
		Key:          "content_extractors.wall_clock_budget",
		Class:        withMutability(classificationFor("content_extractors.wall_clock_budget"), MutabilityStatic),
		Type:         "string",
		Description:  "Max wall-clock time for a single extraction",
		Default:      "30s",
		YAMLPath:     "content_extractors.wall_clock_budget",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_WALL_CLOCK_BUDGET",
		Get:          func(c *Config) string { return c.ContentExtractors.WallClockBudget.String() },
		Transitional: true,
	},
	{
		Key:          "content_extractors.per_user_concurrency_default",
		Class:        withMutability(classificationFor("content_extractors.per_user_concurrency_default"), MutabilityStatic),
		Type:         "int",
		Description:  "Default max concurrent extractions per user",
		Default:      "2",
		YAMLPath:     "content_extractors.per_user_concurrency_default",
		EnvVar:       "TMI_CONTENT_EXTRACTORS_PER_USER_CONCURRENCY_DEFAULT",
		Get:          func(c *Config) string { return strconv.Itoa(c.ContentExtractors.PerUserConcurrencyDefault) },
		Transitional: true,
	},
	// content_extractors.async_enabled is emitted (and classified) under the
	// renamed key extraction.async_enabled — see
	// ExpectedMigratableKeysSkipped's "content_extractors.async_enabled"
	// entry in migratable_discovery.go. YAMLPath still reflects the struct's
	// actual location; Key matches the canonical settings/classification key.
	{
		Key:          "extraction.async_enabled",
		Class:        classificationFor("extraction.async_enabled"),
		Type:         "bool",
		Description:  "Route document extraction through the async worker pipeline instead of inline (default false; requires NATS)",
		Default:      "false",
		YAMLPath:     "content_extractors.async_enabled",
		EnvVar:       "TMI_EXTRACTION_ASYNC_ENABLED",
		Get:          func(c *Config) string { return strconv.FormatBool(c.ContentExtractors.AsyncEnabled) },
		Transitional: true,
	},

	// --- Content OAuth: callback URL (per-provider keys excluded — dynamic cardinality) ---
	{
		Key:           "content_oauth.callback_url",
		Class:         withMutability(classificationFor("content_oauth.callback_url"), MutabilityStatic),
		Type:          "string",
		Description:   "Content OAuth callback URL",
		Default:       "",
		YAMLPath:      "content_oauth.callback_url",
		EnvVar:        "TMI_CONTENT_OAUTH_CALLBACK_URL",
		Get:           func(c *Config) string { return c.ContentOAuth.CallbackURL },
		Transitional:  true,
		OmitWhenEmpty: true,
	},

	// --- Content sources: Google Drive ---
	{
		Key:          "content_sources.google_drive.enabled",
		Class:        withMutability(classificationFor("content_sources.google_drive.enabled"), MutabilityStatic),
		Type:         "bool",
		Description:  "Google Drive content source enabled",
		Default:      "false",
		YAMLPath:     "content_sources.google_drive.enabled",
		EnvVar:       "TMI_CONTENT_SOURCE_GOOGLE_DRIVE_ENABLED",
		Get:          func(c *Config) string { return strconv.FormatBool(c.ContentSources.GoogleDrive.Enabled) },
		Transitional: true,
	},
	{
		Key:           "content_sources.google_drive.service_account_email",
		Class:         withMutability(classificationFor("content_sources.google_drive.service_account_email"), MutabilityStatic),
		Type:          "string",
		Description:   "Google Drive service account email",
		Default:       "",
		YAMLPath:      "content_sources.google_drive.service_account_email",
		EnvVar:        "TMI_CONTENT_SOURCE_GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL",
		Get:           func(c *Config) string { return c.ContentSources.GoogleDrive.ServiceAccountEmail },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.google_drive.credentials_file",
		Class:         withMutability(classificationFor("content_sources.google_drive.credentials_file"), MutabilityStatic),
		Type:          "string",
		Description:   "Google Drive service account credentials file path",
		Default:       "",
		YAMLPath:      "content_sources.google_drive.credentials_file",
		EnvVar:        "TMI_CONTENT_SOURCE_GOOGLE_DRIVE_CREDENTIALS_FILE",
		Get:           func(c *Config) string { return c.ContentSources.GoogleDrive.CredentialsFile },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.google_drive.browser_oauth_client_id",
		Class:         withMutability(classificationFor("content_sources.google_drive.browser_oauth_client_id"), MutabilityStatic),
		Type:          "string",
		Description:   "Google Drive browser OAuth client ID (public)",
		Default:       "",
		YAMLPath:      "content_sources.google_drive.browser_oauth_client_id",
		EnvVar:        "TMI_CONTENT_SOURCE_GOOGLE_DRIVE_BROWSER_OAUTH_CLIENT_ID",
		Get:           func(c *Config) string { return c.ContentSources.GoogleDrive.BrowserOAuthClientID },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.google_drive.picker_developer_key",
		Class:         withMutability(classificationFor("content_sources.google_drive.picker_developer_key"), MutabilityStatic),
		Type:          "string",
		Description:   "Google Drive Picker developer key (public)",
		Default:       "",
		YAMLPath:      "content_sources.google_drive.picker_developer_key",
		EnvVar:        "TMI_CONTENT_SOURCE_GOOGLE_DRIVE_PICKER_DEVELOPER_KEY",
		Get:           func(c *Config) string { return c.ContentSources.GoogleDrive.PickerDeveloperKey },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.google_drive.picker_app_id",
		Class:         withMutability(classificationFor("content_sources.google_drive.picker_app_id"), MutabilityStatic),
		Type:          "string",
		Description:   "Google Drive Picker app ID (public)",
		Default:       "",
		YAMLPath:      "content_sources.google_drive.picker_app_id",
		EnvVar:        "TMI_CONTENT_SOURCE_GOOGLE_DRIVE_PICKER_APP_ID",
		Get:           func(c *Config) string { return c.ContentSources.GoogleDrive.PickerAppID },
		Transitional:  true,
		OmitWhenEmpty: true,
	},

	// --- Content sources: Google Workspace ---
	{
		Key:          "content_sources.google_workspace.enabled",
		Class:        withMutability(classificationFor("content_sources.google_workspace.enabled"), MutabilityStatic),
		Type:         "bool",
		Description:  "Google Workspace content source enabled",
		Default:      "false",
		YAMLPath:     "content_sources.google_workspace.enabled",
		EnvVar:       "TMI_CONTENT_SOURCE_GOOGLE_WORKSPACE_ENABLED",
		Get:          func(c *Config) string { return strconv.FormatBool(c.ContentSources.GoogleWorkspace.Enabled) },
		Transitional: true,
	},
	{
		Key:           "content_sources.google_workspace.picker_developer_key",
		Class:         withMutability(classificationFor("content_sources.google_workspace.picker_developer_key"), MutabilityStatic),
		Type:          "string",
		Description:   "Google Workspace Picker developer key (public)",
		Default:       "",
		YAMLPath:      "content_sources.google_workspace.picker_developer_key",
		EnvVar:        "TMI_CONTENT_SOURCE_GOOGLE_WORKSPACE_PICKER_DEVELOPER_KEY",
		Get:           func(c *Config) string { return c.ContentSources.GoogleWorkspace.PickerDeveloperKey },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.google_workspace.picker_app_id",
		Class:         withMutability(classificationFor("content_sources.google_workspace.picker_app_id"), MutabilityStatic),
		Type:          "string",
		Description:   "Google Workspace Picker app ID (public)",
		Default:       "",
		YAMLPath:      "content_sources.google_workspace.picker_app_id",
		EnvVar:        "TMI_CONTENT_SOURCE_GOOGLE_WORKSPACE_PICKER_APP_ID",
		Get:           func(c *Config) string { return c.ContentSources.GoogleWorkspace.PickerAppID },
		Transitional:  true,
		OmitWhenEmpty: true,
	},

	// --- Content sources: Confluence ---
	{
		Key:          "content_sources.confluence.enabled",
		Class:        withMutability(classificationFor("content_sources.confluence.enabled"), MutabilityStatic),
		Type:         "bool",
		Description:  "Confluence content source enabled",
		Default:      "false",
		YAMLPath:     "content_sources.confluence.enabled",
		EnvVar:       "TMI_CONTENT_SOURCE_CONFLUENCE_ENABLED",
		Get:          func(c *Config) string { return strconv.FormatBool(c.ContentSources.Confluence.Enabled) },
		Transitional: true,
	},

	// --- Content sources: Microsoft ---
	{
		Key:          "content_sources.microsoft.enabled",
		Class:        withMutability(classificationFor("content_sources.microsoft.enabled"), MutabilityStatic),
		Type:         "bool",
		Description:  "Microsoft content source enabled",
		Default:      "false",
		YAMLPath:     "content_sources.microsoft.enabled",
		EnvVar:       "TMI_CONTENT_SOURCE_MICROSOFT_ENABLED",
		Get:          func(c *Config) string { return strconv.FormatBool(c.ContentSources.Microsoft.Enabled) },
		Transitional: true,
	},
	{
		Key:           "content_sources.microsoft.tenant_id",
		Class:         withMutability(classificationFor("content_sources.microsoft.tenant_id"), MutabilityStatic),
		Type:          "string",
		Description:   "Microsoft Entra tenant ID",
		Default:       "",
		YAMLPath:      "content_sources.microsoft.tenant_id",
		EnvVar:        "TMI_CONTENT_SOURCE_MICROSOFT_TENANT_ID",
		Get:           func(c *Config) string { return c.ContentSources.Microsoft.TenantID },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.microsoft.client_id",
		Class:         withMutability(classificationFor("content_sources.microsoft.client_id"), MutabilityStatic),
		Type:          "string",
		Description:   "Microsoft Entra app client ID (public)",
		Default:       "",
		YAMLPath:      "content_sources.microsoft.client_id",
		EnvVar:        "TMI_CONTENT_SOURCE_MICROSOFT_CLIENT_ID",
		Get:           func(c *Config) string { return c.ContentSources.Microsoft.ClientID },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.microsoft.application_object_id",
		Class:         withMutability(classificationFor("content_sources.microsoft.application_object_id"), MutabilityStatic),
		Type:          "string",
		Description:   "Microsoft Entra application object ID",
		Default:       "",
		YAMLPath:      "content_sources.microsoft.application_object_id",
		EnvVar:        "TMI_CONTENT_SOURCE_MICROSOFT_APPLICATION_OBJECT_ID",
		Get:           func(c *Config) string { return c.ContentSources.Microsoft.ApplicationObjectID },
		Transitional:  true,
		OmitWhenEmpty: true,
	},
	{
		Key:           "content_sources.microsoft.picker_origin",
		Class:         withMutability(classificationFor("content_sources.microsoft.picker_origin"), MutabilityStatic),
		Type:          "string",
		Description:   "Microsoft Picker allowed origin URL",
		Default:       "",
		YAMLPath:      "content_sources.microsoft.picker_origin",
		EnvVar:        "TMI_CONTENT_SOURCE_MICROSOFT_PICKER_ORIGIN",
		Get:           func(c *Config) string { return c.ContentSources.Microsoft.PickerOrigin },
		Transitional:  true,
		OmitWhenEmpty: true,
	},

	// --- Top-level: content token encryption key ---
	// content_token_encryption_key has NO entry in exactClassifications or
	// prefixClassifications (classification_registry.go) — classificationFor
	// would return the zero ConfigClass (CategoryUnclassified), which fails
	// validation. Declared here with the bootstrapClass fallback shape
	// instead, with Secret:true: it is an encryption key, and the
	// alternatives (a non-secret classification, or a hardcoded default) are
	// both unsafe.
	{
		Key:         "content_token_encryption_key",
		Class:       bootstrapClass(false, VisibilityInternal, true),
		Type:        "string",
		Description: "Encryption key used to encrypt content provider OAuth tokens at rest",
		Default:     "",
		YAMLPath:    "content_token_encryption_key",
		EnvVar:      "TMI_CONTENT_TOKEN_ENCRYPTION_KEY",
		Get:         func(c *Config) string { return c.ContentTokenEncryptionKey },
	},
}
